### ISSUE TITLE
[BUG]: CommonJS TypeScript files do not find type declarations

### ISSUE THREAD

**Issue by sounisi5011** [mheob/used-pm#17]
### Description of the bug

When importing the used-pm package into a TypeScript file in CommonJS mode, `tsc` reports the following error:

```
foo.cts:1:20 - error TS7016: Could not find a declaration file for module 'used-pm'. '.../node_modules/used-pm/dist/index.cjs' implicitly has an 'any' type.
  If the 'used-pm' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'used-pm';`

1 import usedPM from 'used-pm';
                     ~~~~~~~~~
```

### Steps To Reproduce

0. Go into the new directory and create a `package.json` file with the following contents:

    ```json
    {}
    ```

2. Run `npm install used-pm typescript`
3. Create a `tsconfig.json` file with the following contents:

    ```json
    {
      "compilerOptions": {
        "noImplicitAny": true,
        "moduleResolution": "node16"
      }
    }
    ```

4. Create a `foo.cts` file with the following contents:

    ```ts
    import usedPM from 'used-pm';
    console.log(usedPM());
    ```

5. Run `npx tsc --noEmit`

### Additional Information

If there is an `exports` field in `package.json`, TypeScript will now look for a type declaration file using the `"types"` import condition instead of the `types` field.
see https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

Even if there is no `"types"` import condition, TypeScript will not use the `types` field.
So TypeScript **will not find a type declaration file**.

Therefore, the `exports` field should be written as follows:

```json
{
	"exports": {
		"types": "./dist/index.d.ts",
		"import": "./dist/index.js",
		"require": "./dist/index.cjs"
	}
}
```

**Comment by mheob** [comment]
Thanks for reporting the issue in such detail. A fix will be coming soon.
