### ISSUE TITLE
[BUG]: Release v1.1.0 on NPM is missing build artifacts/dist folder.

### ISSUE THREAD

**Issue by dworthen** [mheob/used-pm#56]
### Description of the bug

I just installed used-pm@1.1.0 and noticed that the package that was pulled down to my node_modules is missing dist directory.

![image](https://github.com/mheob/used-pm/assets/624870/ded8a9d6-f355-4206-8a8e-402615e3b51b)

I checked the code tab in NPM and it appears that dist folder was not published with version 1.1.0. 

![image](https://github.com/mheob/used-pm/assets/624870/623c840a-bda2-4a2e-b905-3f5faf6d56be)

If I am not mistaken, this package is not useable in its current state.  

### Steps To Reproduce

1. `npm install used-pm@1.1.0` and notice that the dist directory is not included. My editor made me aware of this issue as it was not able to locate the types for this package and I got runtime errors trying to use the package as expected.

**Comment by mheob** [comment]
Fixed in v1.1.1
